-- Create Database
CREATE DATABASE IF NOT EXISTS GarageFleetDB;
USE GarageFleetDB;

-- 1. MOTORCYCLE Table
CREATE TABLE MOTORCYCLE (
    ChassisNo VARCHAR(50) PRIMARY KEY,
    RegistrationNo VARCHAR(20) UNIQUE NOT NULL,
    Model VARCHAR(100) NOT NULL,
    EngineType VARCHAR(50),
    OwnerName VARCHAR(100) NOT NULL
);

-- 2. MECHANIC Table
CREATE TABLE MECHANIC (
    MechanicID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Specialization VARCHAR(100) NOT NULL,
    ContactNo VARCHAR(15) UNIQUE NOT NULL
);

-- 3. PARTS_INVENTORY Table
CREATE TABLE PARTS_INVENTORY (
    PartID INT AUTO_INCREMENT PRIMARY KEY,
    PartName VARCHAR(100) NOT NULL,
    Brand VARCHAR(50) NOT NULL,
    Grade VARCHAR(50),
    StockQuantity INT NOT NULL CHECK (StockQuantity >= 0),
    UnitPrice DECIMAL(10,2) NOT NULL CHECK (UnitPrice > 0)
);

-- 4. SERVICE_RECORD Table
CREATE TABLE SERVICE_RECORD (
    ServiceID INT AUTO_INCREMENT PRIMARY KEY,
    ChassisNo VARCHAR(50) NOT NULL,
    MechanicID INT NOT NULL,
    ServiceDate DATE NOT NULL,
    OdometerReading INT NOT NULL CHECK (OdometerReading > 0),
    TotalCost DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (ChassisNo) REFERENCES MOTORCYCLE(ChassisNo) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (MechanicID) REFERENCES MECHANIC(MechanicID) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- 5. SERVICE_LINE_ITEM Table (Resolves M:N)
CREATE TABLE SERVICE_LINE_ITEM (
    ServiceID INT,
    PartID INT,
    QuantityUsed DECIMAL(5,2) NOT NULL CHECK (QuantityUsed > 0),
    PRIMARY KEY (ServiceID, PartID),
    FOREIGN KEY (ServiceID) REFERENCES SERVICE_RECORD(ServiceID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (PartID) REFERENCES PARTS_INVENTORY(PartID) ON DELETE RESTRICT ON UPDATE CASCADE
);